version: '3.9'

services:
  postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
    hostname: db

  nginx:
    build: ./nginx
    depends_on:
      - api
    volumes:
      - ./html
    ports:
      - 8181:80
    networks:
      - backend
    hostname: nginx

  app:
    build: ./app
    depends_on:
      - db-postgres
    volumes:
      - ./app
      - ./static
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - backend
    hostname: app

networks:
  backend:
    name: backend
